spring:
  application:
    name: ms-finanzas
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:aws-1-us-east-2.pooler.supabase.com}:${DB_PORT:6543}/${DB_NAME:postgres}
    username: ${DB_USER:postgres.aagdzusmeniqghpykyxs}
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
      idle-timeout: 10000
      max-lifetime: 30000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:public}
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  cloud:
    config:
      enabled: false
eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when_authorized
    prometheus:
      access: unrestricted
  metrics:
    tags:
      application: ${spring.application.name}

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET:YmFzZS02NC1lbmNvZGVkLXNlY3JldC1rZXktZm9yLWp3dC10b2tlbi1hdXRoZW50aWNhdGlvbg==}
  expiration: ${JWT_EXPIRATION:86400000}